### ISSUE TITLE
Build NetBox Community Landing Page

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-community.github.io#1]
**To-Do:**
- [ ] Create dev branch for staging changes before deploying
- [ ] Pick A Jekyll Theme
- [ ] Define sections & content
- [ ] Build a draft site
- [ ] Document process for adding content & updating site

**Comment by ryanmerolle** [comment]
@jeremystretch - Thoughts?

Possible Sections:

- Landing/About
- Blog
- Sponsors
- Repos/projects (detailing each community project with a link to repo, readme)
- Curated Unaffiliated podcast episodes, blog posts, plugins(just a link for the GitHub topic
- Link to the demo and beta


Theme Priorities:

1. Minimal
2. Product/Community Resource focused (ie not focusing on blogging)

Possible Jekyll Themes:

- [Hyde](https://jekyllthemes.io/theme/hyde)
- [Automatic](https://emilbaehr.github.io/automatic-app-landing-page)
- [SinglePaged](http://t413.com/SinglePaged/)
- Need to keep looking
-
